### ISSUE TITLE
Port to Linux

### ISSUE THREAD

**Issue by kriolog** [google/orbit#4] opened 2017-09-26 02:24 UTC
Feature request.
I certainly need this awesome profiler on my Debian and I think I'm not alone. :) So I propose to port it to Linux together. For the beginning, I could add a CMake-based build.

**Comment by pierricgimmig** [comment] 2017-09-26 12:26
Hi, thanks for your interest!  Porting to linux would be great indeed.  There is a bit of Windows specific code that we would need to factor out (process and module enumeration, pdb parsing, injection) but the corresponding functionality is available on linux.  A great first step would be to make Orbit compile and be able to launch the UI.  A CMake-based build would be perfect.  

One or two other people have shown interest in porting Orbit to linux, we should coordinate our efforts to avoid work duplication, perhaps using this thread.

**Comment by DanOlivier** [comment] 2017-10-04 12:53
Yeah. So the problem isn't to implement the build system in cmake.
This can be done in parallel with Visual Studio, or not (with the goal of replacing the projects and allowing them to be generated, or not). 

## 3rd-party dependencies

Instead of committing yet more binaries into the repo (a discouraged practice), to match various combinations of OS and compiler, CMake should only ever be responsible for detecting the various components, at least for major components that are commonly available (and that are not too costly to recompile).

On my distro (Ubuntu), I would like to use (whatever versions of) the 3rd-party libraries available from public repositories (or forked versions that I install myself and that I control).

Here are some of the differences:
- Available with Ubuntu versions (compared to repository version in parenthesis):
  - **freeglut3**: 2.8.1 (same)
  - **libcurl**: 7.52.1 (same)
  - **websocketpp**: 0.7.0 (same)
  - **freetype2**: 2.6.3 (**downgrade** 2.7.1 in repo)
  - **glew**: 2.0.0 (why do you need both versions 1.13 and 2.0 in the repository?)
  - **asio**: 1.10.8 (**downgrade** 1.11.0)
  - **cereal**: 1.2.1 (**upgrade** 1.1.2 in repo)
  - **capstone**: 3.0.4 (**downgrade** 3.0.5 in Orbit repository)
  - **Qt5**: 5.7.1. Nothing was checked-into the repository, expecting (I suppose) to find it installed in well-known locations (QTDIR).
- Remain external (unavailable on Ubuntu):
  - **oqpi**: doesn't look like it's portable, no Linux implementations for commonly available functions (already available elsewhere)
  - **imgui**: this is a well-supported library and shouldn't cause any problems
  - **stlsoft**: had to hack the platform checks. Looks old.
  - **xxHash-r42**
  - **freetype-gl** (which has embedded versions of freetype, glew and AntTweakBar, whatever that is).
    I thought this might be a copy of libftgl, but I guess not.
  - **breakpad**
  - **Qt property browser**
  - various others

## Portability (away from Windows)

Here's what we already knew we would have to change: 
- different debug info format, 
- different intercept assembly instructions, etc.

The problem, IMO, is that for the part of the program I have started investigating (OrbitCore), I can't find anything that isn't Windows-dependent (using Windows-specific \#includes, definitions, symbols and conventions).
- WCHAR vs wchar_t, UNICODE, OuptputDebugString, vsnprintf_s secure
- I'm using a package called 'winpr' to provide Linux-compatible versions of some symbols and function, but I am not familiar with it and may not be using it to its full potential.
- much more stuff here, since I'm just getting started...

I seem to have gotten through OrbitQt relatively well (the build is duplicated here by the Qt tooling, i.e. more makefiles).

This (ubiquitous dependency on Windows) is really beyond what I had expected.

Eventually (imminently?), we need to build interfaces to protect and hide the platform-specific definitions. Right now, this is looking like a much bigger job than I thought (not a total rewrite, but for some parts, almost).

I've forked ([here](https://github.com/DanOlivier/orbitprofiler)) the Orbit repository to my own Github account, and when I have something ready that won't break the Windows build, I'll create a pull request. 

I have removed the 3rd-party directories for those components that are already available on my system, and would recommend they be (eventually) re-added as submodules (making them optional?).

**Comment by pierricgimmig** [comment] 2017-10-05 04:44
Hi Dan, thanks for your detailed analysis.  It looks like the port will need a bit of work :-).   FYI, some of the third party libs are barely used.  Oqpi for example could be replaced by C++ 11's parallel for loops.  Stlsoft is basically used as a wrapper over QueryPerformanceCounter...  I'll look at your fork, and start cleaning up some more code on my side.  I'd like to start a Mac port soon.  Thanks again.

**Comment by florian-kuebler** [comment] 2020-06-16 06:28
@pierricgimmig, @beckerhe, we should be able to close this now, right?

**Comment by dimitry-** [comment] 2020-06-16 09:42
I believe this is fixed.

**Closed by dimitry-** 2020-06-16 09:42 UTC
